spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bgm?characterEncoding=UTF-8
    username: root
    password: 0528
    hikari:
      auto-commit: false
      pool-name: bgmlab-connection-pool
      minimum-idle: 10
      maximum-pool-size: 20
      connection-timeout: 60000
      max-lifetime: 1800000
      idle-timeout: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

token:
  secret: 91f922ca017c4c9a0879aa850ec9aa75da54d17c487cbdda584ef19e69bf35aa
  expiration:
    access: 86400
    refresh: 604800

app:
  headers:
    auth-token: Authorization

oauth2:
  client:
    registration:
      kakao:
        client-id: 680f2b0c498c5f52a46943fb31e038a9
        client-secret: Z5Kmo64LALDza5IhmoyXcKNTseWVJvEu
        redirect-uri: "http://localhost:8080/oauth/kakao"
    provider:
      kakao:
        authorization-uri: https://kauth.kakao.com/oauth/token
        login-uri: https://kapi.kakao.com/v2/user/me
