spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bgm?characterEncoding=UTF-8
    username: root
    password: 0528
    hikari:
      auto-commit: false
      pool-name: gasomann-pool
      minimum-idle: 10
      maximum-pool-size: 20
      connection-timeout: 60000
      max-lifetime: 1800000
      idle-timeout: 60000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
